In [2]:
import pandas as pd
import numpy as np

In [3]:
data_train = pd.read_csv("train.csv")
data_submiss = pd.read_csv("test.csv")

In [5]:
data_train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [7]:
data_submiss.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [10]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 208.2+ KB


In [11]:
data_submiss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3263 entries, 0 to 3262
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        3263 non-null   int64 
 1   keyword   3237 non-null   object
 2   location  2158 non-null   object
 3   text      3263 non-null   object
dtypes: int64(1), object(3)
memory usage: 63.8+ KB


In [1]:
import nltk

In [105]:
from sklearn.model_selection import train_test_split, cross_val_score

In [26]:
#train, test = train_test_split(data_train, test_size=0.3)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [137]:
vector = CountVectorizer(stop_words=None, ngram_range=(1,1))

In [164]:
vector2 = TfidfVectorizer()

In [290]:
features = vector2.fit_transform(data_train['text'])

In [292]:
from sklearn.linear_model import SGDClassifier, RidgeClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

In [248]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [247]:
clf = SGDClassifier(loss='squared_hinge', penalty='l2', alpha=1e-3, random_state=48, max_iter=50, tol=1e-4)

score = cross_val_score(clf, features, data_train.target, cv=3)

print(f"{score}\n{score.mean()}")

[0.74113475 0.71631206 0.75955853]
0.7390017807372868


In [150]:
clf2 = RidgeClassifier()

score = cross_val_score(clf2, features, data_train.target, cv=3)
print(f"{score}\n{score.mean()}")

[0.73758865 0.70055162 0.75246354]
0.7302012691804064


In [293]:
clf3 = LinearSVC()

score = cross_val_score(clf3, features, data_train.target, cv=3)
print(f"{score}\n{score.mean()}")

[0.73049645 0.69227738 0.74024438]
0.7210060735990451


In [291]:
clf4 = MultinomialNB(alpha=0.8)

score = cross_val_score(clf4, features, data_train.target, cv=3)
print(f"{score}\n{score.mean()}")

[0.74349882 0.71237195 0.78202601]
0.7459655931199078


In [296]:
target_example = pd.read_csv("sample_submission.csv")
target_example.head()

id  target
0   0       0
1   2       0
2   3       0
3   9       0
4  11       0

In [301]:
clf4.fit(features, data_train.target)

pred = clf4.predict(vector2.transform(data_submiss['text']))
print(f"{accuracy_score(target_example.target, pred)}")

0.69414649095924
