In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [98]:
# Importando CSV de treino
# Importanto CSV de validação do kaggle

df_train = pd.read_csv("../dados_titanic/train.csv")
df_submission = pd.read_csv("../dados_titanic/test.csv")


In [99]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 66.2+ KB


In [100]:
df_submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Pclass       418 non-null    int64  
 2   Name         418 non-null    object 
 3   Sex          418 non-null    object 
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
dtypes: float64(2), int64(4), object(5)
memory usage: 27.8+ KB


# ANALISANDO O DATASET

In [6]:
df_train[df_train['Embarked'].isna()]

PassengerId  Survived  Pclass                                       Name  \
61            62         1       1                        Icard, Miss. Amelie   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket  Fare Cabin Embarked  
61   female  38.0      0      0  113572  80.0   B28      NaN  
829  female  62.0      0      0  113572  80.0   B28      NaN

In [13]:
df_train[df_train['Age'].isna()]

PassengerId  Survived  Pclass                                      Name  \
5              6         0       3                          Moran, Mr. James   
17            18         1       2              Williams, Mr. Charles Eugene   
19            20         1       3                   Masselmani, Mrs. Fatima   
26            27         0       3                   Emir, Mr. Farred Chehab   
28            29         1       3             O'Dwyer, Miss. Ellen "Nellie"   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
5      male  NaN      0      0      330877   8.4583   NaN        Q  
17     male  NaN      0      0      244373  13.0000   NaN        S  
19   female  NaN      0      0        2649   7.2250   NaN        C  
26     male  NaN      0      0        2631   7.2250   NaN        C  
28   female  NaN      0      0      330959   7.8792   NaN        Q  
..      ...  ...    ...    ...         ...      ...   ...      ...  
859    male  NaN      0      0        2629   7.2292   NaN        C  
863  female  NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male  NaN      0      0      345777   9.5000   NaN        S  
878    male  NaN      0      0      349217   7.8958   NaN        S  
888  female  NaN      1      2  W./C. 6607  23.4500   NaN        S  

[177 rows x 12 columns]

In [14]:
df_submission[df_submission['Age'].isna()]

PassengerId  Pclass                                               Name  \
10           902       3                                   Ilieff, Mr. Ylio   
22           914       1               Flegenheim, Mrs. Alfred (Antoinette)   
29           921       3                                  Samaan, Mr. Elias   
33           925       3  Johnston, Mrs. Andrew G (Elizabeth Lily" Watson)"   
36           928       3                                Roth, Miss. Sarah A   
..           ...     ...                                                ...   
408         1300       3                    Riordan, Miss. Johanna Hannah""   
410         1302       3                             Naughton, Miss. Hannah   
413         1305       3                                 Spector, Mr. Woolf   
416         1308       3                                Ware, Mr. Frederick   
417         1309       3                           Peter, Master. Michael J   

        Sex  Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
10     male  NaN      0      0      349220   7.8958   NaN        S  
22   female  NaN      0      0    PC 17598  31.6833   NaN        S  
29     male  NaN      2      0        2662  21.6792   NaN        C  
33   female  NaN      1      2  W./C. 6607  23.4500   NaN        S  
36   female  NaN      0      0      342712   8.0500   NaN        S  
..      ...  ...    ...    ...         ...      ...   ...      ...  
408  female  NaN      0      0      334915   7.7208   NaN        Q  
410  female  NaN      0      0      365237   7.7500   NaN        Q  
413    male  NaN      0      0   A.5. 3236   8.0500   NaN        S  
416    male  NaN      0      0      359309   8.0500   NaN        S  
417    male  NaN      1      1        2668  22.3583   NaN        C  

[86 rows x 11 columns]

In [15]:
df_submission[df_submission['Fare'].isna()]

PassengerId  Pclass                Name   Sex   Age  SibSp  Parch Ticket  \
152         1044       3  Storey, Mr. Thomas  male  60.5      0      0   3701   

     Fare Cabin Embarked  
152   NaN   NaN        S

In [110]:
df_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin  Embarked  Sex_bin  Family_size  \
0      0         A/5 21171   7.2500   NaN         1        0            1   
1      0          PC 17599  71.2833   C85         2        1            1   
2      0  STON/O2. 3101282   7.9250   NaN         1        1            0   
3      0            113803  53.1000  C123         1        1            1   
4      0            373450   8.0500   NaN         1        0            0   

   Title  
0    Mr.  
1   Mrs.  
2  Miss.  
3   Mrs.  
4    Mr.

In [111]:
df_submission.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin  Embarked  Sex_bin  Family_size  \
0  34.5      0      0   330911   7.8292   NaN         3        0            0   
1  47.0      1      0   363272   7.0000   NaN         1        1            1   
2  62.0      0      0   240276   9.6875   NaN         3        0            0   
3  27.0      0      0   315154   8.6625   NaN         1        0            0   
4  22.0      1      1  3101298  12.2875   NaN         1        1            2   

  Title  
0   Mr.  
1  Mrs.  
2   Mr.  
3   Mr.  
4  Mrs.

# Preparando DATASET

In [101]:
# Preenchendo os embarques faltantes no DataSet de treino
# A escolha do "C" foi devido a relação entre Embarque e valor do Ticket

df_train['Embarked'] = df_train['Embarked'].fillna('C')

In [102]:
# Preenchendo os valores de tickets faltantes no DataSet de submissao
# A escolha do valor foi devido a relaçao com onde embarcaram

df_submission['Fare'] = df_submission['Fare'].fillna(28)

In [103]:
# Preenchendo idades faltantes em ambos DataSets

# Criterio de preenchimento
# DataSet de Treino
# Para os vivos, a media de idade dos que estão vivos
# Para os mortos, a media de idade dos que estão mortos

train_alive_mean = df_train[df_train['Survived'] == 1].copy()['Age'].mean()
train_dead_mean = df_train[df_train['Survived'] == 0].copy()['Age'].mean()


In [104]:
df_train.loc[df_train['Survived'] == 1, 'Age'] = df_train.loc[df_train['Survived'] == 1, ['Age']].fillna(train_alive_mean)

df_train.loc[df_train['Survived'] == 0, 'Age'] = df_train.loc[df_train['Survived'] == 0, ['Age']].fillna(train_dead_mean)

In [105]:
# Criterio de preenchimento
# DataSet de submissao
# A media de idade geral para os faltantes

df_submission['Age'] = df_submission['Age'].fillna(df_submission['Age'].mean())

In [106]:
# Transformando os campos "Embarked" em numericos

embarked_numerico = {'S':1,'C':2,'Q':3}
df_train['Embarked'] = df_train['Embarked'].map(embarked_numerico)
df_submission['Embarked'] = df_submission['Embarked'].map(embarked_numerico)

In [107]:
# Transformando o "Sex" em binario e criando a nova coluna "Sex_bin"

# poderia ter utilizado o metodo """pd.get_dummies(variable['column'])""" porem utilizei uma lambda para criar uma nova coluna

#df_train['Sex'] = pd.get_dummies(df_train['Sex'])
#df_submission['Sex'] = pd.get_dummies(df_submission['Sex'])

df_train['Sex_bin'] = df_train['Sex'].map(lambda x: 1 if x == 'female' else 0)
df_submission['Sex_bin'] = df_submission['Sex'].map(lambda x: 1 if x == 'female' else 0)

In [108]:
# Transformando as colunas "SibSp" e "Parch" em apenas uma coluna
# Definindo uma coluna como tamanho da familia "Family_size"

df_train['Family_size'] = df_train['SibSp'] + df_train['Parch']
df_submission['Family_size'] = df_submission['SibSp'] + df_submission['Parch']

In [109]:
# Trabalhando com os nomes dos tripulantes
# Criando a coluna "Title", (todos os nomes tem algum titulo: Ex: Mrs., Miss., Master.)

df_train['Title'] = df_train['Name'].map(lambda x: x.split(',')[1].split()[0])
df_submission['Title'] = df_submission['Name'].map(lambda x: x.split(',')[1].split()[0])

# Analisando a correlação entre as variaveis

In [98]:
df_train.corr()

PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.035652 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.085364 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.327130  0.083081  0.018443   
Age             0.035652 -0.085364 -0.327130  1.000000 -0.230465 -0.179217   
SibSp          -0.057527 -0.035322  0.083081 -0.230465  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.179217  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.089267  0.159651  0.216225   
Embarked       -0.030444  0.111203  0.040138  0.009865 -0.061591 -0.080277   
Sex_bin        -0.042939  0.543351 -0.131900 -0.092957  0.114631  0.245489   

                 Fare  Embarked   Sex_bin  
PassengerId  0.012658 -0.030444 -0.042939  
Survived     0.257307  0.111203  0.543351  
Pclass      -0.549500  0.040138 -0.131900  
Age          0.089267  0.009865 -0.092957  
SibSp        0.159651 -0.061591  0.114631  
Parch        0.216225 -0.080277  0.245489  
Fare         1.000000  0.065492  0.182333  
Embarked     0.065492  1.000000  0.121266  
Sex_bin      0.182333  0.121266  1.000000

In [102]:
df_train[["Parch", "Survived"]].groupby(['Parch'], as_index=False).mean().sort_values(by='Survived', ascending=False)

Parch  Survived
3      3  0.600000
1      1  0.550847
2      2  0.500000
0      0  0.343658
5      5  0.200000
4      4  0.000000
6      6  0.000000

In [108]:
df_train[['Family_size', 'Survived']].groupby(['Family_size'], as_index=False).mean().sort_values(by='Survived', ascending=False)

Family_size  Survived
3            3  0.724138
2            2  0.578431
1            1  0.552795
6            6  0.333333
0            0  0.303538
4            4  0.200000
5            5  0.136364
7            7  0.000000
8           10  0.000000

In [125]:
df_train[['Title', 'Survived']].groupby(['Title'], as_index=False).mean().sort_values(by='Survived', ascending=False)

Title  Survived
16        the  1.000000
9       Mlle.  1.000000
15       Sir.  1.000000
13        Ms.  1.000000
5       Lady.  1.000000
10       Mme.  1.000000
12       Mrs.  0.792000
8       Miss.  0.697802
7     Master.  0.575000
1        Col.  0.500000
6      Major.  0.500000
3         Dr.  0.428571
11        Mr.  0.156673
4   Jonkheer.  0.000000
14       Rev.  0.000000
2        Don.  0.000000
0       Capt.  0.000000

In [112]:
variaveis = ['Pclass','Age','Fare','Embarked','Sex_bin','Family_size']

In [113]:
X = df_train[variaveis]
y = df_train['Survived']

In [114]:
X.head()

Pclass   Age     Fare  Embarked  Sex_bin  Family_size
0       3  22.0   7.2500         1        0            1
1       1  38.0  71.2833         2        1            1
2       3  26.0   7.9250         1        1            0
3       1  35.0  53.1000         1        1            1
4       3  35.0   8.0500         1        0            0

# TESTES MODELOS
# VALIDAÇÃO CRUZADA

In [31]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.neural_network import MLPClassifier

from sklearn.linear_model import SGDClassifier

from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import KFold, train_test_split

In [115]:
kf = KFold(3, shuffle=True, random_state=0)

In [116]:
classifier = RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=5, class_weight='balanced', criterion='entropy', max_depth=10)

In [117]:
results = []
for train, valid in kf.split(X):
    X_train, X_valid = X.iloc[train], X.iloc[valid]
    y_train, y_valid = y.iloc[train], y.iloc[valid]

    classifier.fit(X_train, y_train)

    pred = classifier.predict(X_valid)
    print(f"{accuracy_score(y_valid, pred)}\n {confusion_matrix(y_valid, pred)}\n")
    results.append(accuracy_score(y_valid, pred))

np.mean(results)

0.8686868686868687
 [[168  18]
 [ 21  90]]

0.8484848484848485
 [[168  25]
 [ 20  84]]

0.8383838383838383
 [[155  15]
 [ 33  94]]



0.8518518518518517

In [118]:
classifier.fit(X,y)

RandomForestClassifier(class_weight='balanced', criterion='entropy',
                       max_depth=10, n_estimators=200, n_jobs=-1,
                       random_state=5)

In [119]:
teste_train = classifier.predict(X)
classifier.score(X,y)

0.9595959595959596

In [120]:
result_submiss = classifier.predict(df_submission[variaveis])
result_submiss

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [71]:
primeira_submissao = pd.DataFrame({'PassengerId':df_submission['PassengerId'],'Survived':result_submiss})
primeira_submissao.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [72]:
primeira_submissao.to_csv('First_Submission_Titanic.csv', index=False)

In [121]:
segunda_submissao = pd.DataFrame({'PassengerId':df_submission['PassengerId'],'Survived':result_submiss})
segunda_submissao.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

In [123]:
segunda_submissao.to_csv('Second_Submission_Titanic.csv', index=False)

In [122]:
imcompativeis = [v for v,i in zip(primeira_submissao['Survived'], segunda_submissao['Survived']) if v != i]
len(imcompativeis)

21